name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Set ReCaptcha Site Key
        # run: sed -i 's/6LfrqrwZAAAAAIG5jGLIsLFLpVj0V0K52AddS0he/6Lc9j7YZAAAAAOx71vGQuwqqcaALIwLxRDgPpsmL/' contact.html
      - uses: acorn-io/actions-setup@v2
        with:
          acorn-version: main
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          acorn build --push -t ghcr.io/${{ github.repository_owner }}/website:latest .
